-- Jason Rodgers
USE Pizzeria;

DROP TABLE IF EXISTS PizzaTopping;
DROP TABLE IF EXISTS DiscountPizza;
DROP TABLE IF EXISTS DiscountOrder;
DROP TABLE IF EXISTS Pizza;
DROP TABLE IF EXISTS Base;
DROP TABLE IF EXISTS DineInOrder;
DROP TABLE IF EXISTS SeatNum;
DROP TABLE IF EXISTS OrderPickup;
DROP TABLE IF EXISTS OrderDelivery;
DROP TABLE IF EXISTS CustomerDelivery;
DROP TABLE IF EXISTS CustomerPickup;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Topping;
DROP TABLE IF EXISTS Discount;
